# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_likes',
        ),
    ]
