# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_likes',
            field=models.IntegerField(default='2'),
        ),
    ]
