# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20171217_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='azaza_name',
        ),
        migrations.RemoveField(
            model_name='azaza',
            name='azaza_text',
        ),
    ]
