# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_azaza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azaza',
            name='azaza_title',
            field=models.CharField(max_length=200),
        ),
    ]
